
var __cov_BYTQxMqw5xx2dgj3h8Avqw = (Function('return this'))();
if (!__cov_BYTQxMqw5xx2dgj3h8Avqw.__coverage__) { __cov_BYTQxMqw5xx2dgj3h8Avqw.__coverage__ = {}; }
__cov_BYTQxMqw5xx2dgj3h8Avqw = __cov_BYTQxMqw5xx2dgj3h8Avqw.__coverage__;
if (!(__cov_BYTQxMqw5xx2dgj3h8Avqw['app/scripts/modules/home/show/show_view.js'])) {
   __cov_BYTQxMqw5xx2dgj3h8Avqw['app/scripts/modules/home/show/show_view.js'] = {"path":"app/scripts/modules/home/show/show_view.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0},"b":{"1":[0,0],"2":[0,0]},"f":{"1":0,"2":0,"3":0},"fnMap":{"1":{"name":"(anonymous_1)","line":5,"loc":{"start":{"line":5,"column":1},"end":{"line":5,"column":13}}},"2":{"name":"(anonymous_2)","line":7,"loc":{"start":{"line":7,"column":36},"end":{"line":7,"column":85}}},"3":{"name":"(anonymous_3)","line":19,"loc":{"start":{"line":19,"column":18},"end":{"line":19,"column":35}}}},"statementMap":{"1":{"start":{"line":2,"column":0},"end":{"line":4,"column":1}},"2":{"start":{"line":3,"column":2},"end":{"line":3,"column":20}},"3":{"start":{"line":5,"column":0},"end":{"line":27,"column":5}},"4":{"start":{"line":7,"column":2},"end":{"line":26,"column":5}},"5":{"start":{"line":12,"column":4},"end":{"line":23,"column":7}},"6":{"start":{"line":20,"column":8},"end":{"line":20,"column":57}}},"branchMap":{"1":{"line":2,"type":"if","locations":[{"start":{"line":2,"column":0},"end":{"line":2,"column":0}},{"start":{"line":2,"column":0},"end":{"line":2,"column":0}}]},"2":{"line":2,"type":"binary-expr","locations":[{"start":{"line":2,"column":4},"end":{"line":2,"column":17}},{"start":{"line":2,"column":21},"end":{"line":2,"column":53}}]}}};
}
__cov_BYTQxMqw5xx2dgj3h8Avqw = __cov_BYTQxMqw5xx2dgj3h8Avqw['app/scripts/modules/home/show/show_view.js'];
__cov_BYTQxMqw5xx2dgj3h8Avqw.s['1']++;if((__cov_BYTQxMqw5xx2dgj3h8Avqw.b['2'][0]++,!this.AppName)||(__cov_BYTQxMqw5xx2dgj3h8Avqw.b['2'][1]++,typeof this.AppName!=='object')){__cov_BYTQxMqw5xx2dgj3h8Avqw.b['1'][0]++;__cov_BYTQxMqw5xx2dgj3h8Avqw.s['2']++;this.AppName={};}else{__cov_BYTQxMqw5xx2dgj3h8Avqw.b['1'][1]++;}__cov_BYTQxMqw5xx2dgj3h8Avqw.s['3']++;(function(){'use strict';__cov_BYTQxMqw5xx2dgj3h8Avqw.f['1']++;__cov_BYTQxMqw5xx2dgj3h8Avqw.s['4']++;AppName.module('HomeModule.Show',function(Show,App,Backbone,Marionette,$,_){__cov_BYTQxMqw5xx2dgj3h8Avqw.f['2']++;__cov_BYTQxMqw5xx2dgj3h8Avqw.s['5']++;Show.View=Backbone.Marionette.ItemView.extend({template:'home/show/show_view',initialize:function(options){__cov_BYTQxMqw5xx2dgj3h8Avqw.f['3']++;__cov_BYTQxMqw5xx2dgj3h8Avqw.s['6']++;console.log('HomeModule.Show.View initializing');}});});}());
