
var __cov_a$2bcG3atn$RDfsRjHEVxA = (Function('return this'))();
if (!__cov_a$2bcG3atn$RDfsRjHEVxA.__coverage__) { __cov_a$2bcG3atn$RDfsRjHEVxA.__coverage__ = {}; }
__cov_a$2bcG3atn$RDfsRjHEVxA = __cov_a$2bcG3atn$RDfsRjHEVxA.__coverage__;
if (!(__cov_a$2bcG3atn$RDfsRjHEVxA['app/scripts/modules/home/show/show_controller.js'])) {
   __cov_a$2bcG3atn$RDfsRjHEVxA['app/scripts/modules/home/show/show_controller.js'] = {"path":"app/scripts/modules/home/show/show_controller.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0},"b":{"1":[0,0],"2":[0,0]},"f":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0},"fnMap":{"1":{"name":"(anonymous_1)","line":6,"loc":{"start":{"line":6,"column":1},"end":{"line":6,"column":13}}},"2":{"name":"(anonymous_2)","line":11,"loc":{"start":{"line":11,"column":38},"end":{"line":11,"column":87}}},"3":{"name":"(anonymous_3)","line":18,"loc":{"start":{"line":18,"column":24},"end":{"line":18,"column":41}}},"4":{"name":"(anonymous_4)","line":27,"loc":{"start":{"line":27,"column":21},"end":{"line":27,"column":31}}},"5":{"name":"(anonymous_5)","line":33,"loc":{"start":{"line":33,"column":20},"end":{"line":33,"column":32}}},"6":{"name":"(anonymous_6)","line":45,"loc":{"start":{"line":45,"column":21},"end":{"line":45,"column":32}}}},"statementMap":{"1":{"start":{"line":2,"column":0},"end":{"line":4,"column":1}},"2":{"start":{"line":3,"column":4},"end":{"line":3,"column":22}},"3":{"start":{"line":6,"column":0},"end":{"line":54,"column":5}},"4":{"start":{"line":11,"column":4},"end":{"line":52,"column":7}},"5":{"start":{"line":16,"column":8},"end":{"line":50,"column":11}},"6":{"start":{"line":19,"column":16},"end":{"line":19,"column":32}},"7":{"start":{"line":20,"column":16},"end":{"line":20,"column":49}},"8":{"start":{"line":28,"column":14},"end":{"line":28,"column":35}},"9":{"start":{"line":34,"column":16},"end":{"line":34,"column":32}},"10":{"start":{"line":46,"column":16},"end":{"line":46,"column":71}}},"branchMap":{"1":{"line":2,"type":"if","locations":[{"start":{"line":2,"column":0},"end":{"line":2,"column":0}},{"start":{"line":2,"column":0},"end":{"line":2,"column":0}}]},"2":{"line":2,"type":"binary-expr","locations":[{"start":{"line":2,"column":4},"end":{"line":2,"column":17}},{"start":{"line":2,"column":21},"end":{"line":2,"column":53}}]}}};
}
__cov_a$2bcG3atn$RDfsRjHEVxA = __cov_a$2bcG3atn$RDfsRjHEVxA['app/scripts/modules/home/show/show_controller.js'];
__cov_a$2bcG3atn$RDfsRjHEVxA.s['1']++;if((__cov_a$2bcG3atn$RDfsRjHEVxA.b['2'][0]++,!this.AppName)||(__cov_a$2bcG3atn$RDfsRjHEVxA.b['2'][1]++,typeof this.AppName!=='object')){__cov_a$2bcG3atn$RDfsRjHEVxA.b['1'][0]++;__cov_a$2bcG3atn$RDfsRjHEVxA.s['2']++;this.AppName={};}else{__cov_a$2bcG3atn$RDfsRjHEVxA.b['1'][1]++;}__cov_a$2bcG3atn$RDfsRjHEVxA.s['3']++;(function(){'use strict';__cov_a$2bcG3atn$RDfsRjHEVxA.f['1']++;__cov_a$2bcG3atn$RDfsRjHEVxA.s['4']++;AppName.module('HomeModule.Show',function(Show,App,Backbone,Marionette,$,_){__cov_a$2bcG3atn$RDfsRjHEVxA.f['2']++;__cov_a$2bcG3atn$RDfsRjHEVxA.s['5']++;Show.Controller=App.Controllers.Base.extend({initialize:function(options){__cov_a$2bcG3atn$RDfsRjHEVxA.f['3']++;__cov_a$2bcG3atn$RDfsRjHEVxA.s['6']++;_.bindAll(this);__cov_a$2bcG3atn$RDfsRjHEVxA.s['7']++;this.pageName='page:home:show';},initMap:function(){__cov_a$2bcG3atn$RDfsRjHEVxA.f['4']++;__cov_a$2bcG3atn$RDfsRjHEVxA.s['8']++;this._execMapReset();},initUi:function(){__cov_a$2bcG3atn$RDfsRjHEVxA.f['5']++;__cov_a$2bcG3atn$RDfsRjHEVxA.s['9']++;_.bindAll(this);},onClose:function(e){__cov_a$2bcG3atn$RDfsRjHEVxA.f['6']++;__cov_a$2bcG3atn$RDfsRjHEVxA.s['10']++;console.log('CLEANING: HomeModule.show.onClose fired');}});});}());
