
var __cov_9SQU6$TIyGDcy8cuQh5qFA = (Function('return this'))();
if (!__cov_9SQU6$TIyGDcy8cuQh5qFA.__coverage__) { __cov_9SQU6$TIyGDcy8cuQh5qFA.__coverage__ = {}; }
__cov_9SQU6$TIyGDcy8cuQh5qFA = __cov_9SQU6$TIyGDcy8cuQh5qFA.__coverage__;
if (!(__cov_9SQU6$TIyGDcy8cuQh5qFA['app/scripts/modules/home/home_module.js'])) {
   __cov_9SQU6$TIyGDcy8cuQh5qFA['app/scripts/modules/home/home_module.js'] = {"path":"app/scripts/modules/home/home_module.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0},"b":{"1":[0,0],"2":[0,0],"3":[0,0],"4":[0,0]},"f":{"1":0,"2":0,"3":0,"4":0,"5":0},"fnMap":{"1":{"name":"(anonymous_1)","line":5,"loc":{"start":{"line":5,"column":1},"end":{"line":5,"column":13}}},"2":{"name":"(anonymous_2)","line":9,"loc":{"start":{"line":9,"column":33},"end":{"line":9,"column":88}}},"3":{"name":"(anonymous_3)","line":21,"loc":{"start":{"line":21,"column":34},"end":{"line":21,"column":53}}},"4":{"name":"(anonymous_4)","line":27,"loc":{"start":{"line":27,"column":18},"end":{"line":27,"column":35}}},"5":{"name":"(anonymous_5)","line":35,"loc":{"start":{"line":35,"column":19},"end":{"line":35,"column":36}}}},"statementMap":{"1":{"start":{"line":2,"column":0},"end":{"line":4,"column":1}},"2":{"start":{"line":3,"column":4},"end":{"line":3,"column":22}},"3":{"start":{"line":5,"column":0},"end":{"line":45,"column":5}},"4":{"start":{"line":9,"column":4},"end":{"line":44,"column":7}},"5":{"start":{"line":12,"column":8},"end":{"line":18,"column":11}},"6":{"start":{"line":21,"column":8},"end":{"line":23,"column":11}},"7":{"start":{"line":22,"column":12},"end":{"line":22,"column":63}},"8":{"start":{"line":26,"column":8},"end":{"line":42,"column":10}},"9":{"start":{"line":29,"column":16},"end":{"line":31,"column":17}},"10":{"start":{"line":30,"column":18},"end":{"line":30,"column":80}},"11":{"start":{"line":33,"column":16},"end":{"line":33,"column":52}},"12":{"start":{"line":36,"column":16},"end":{"line":38,"column":17}},"13":{"start":{"line":37,"column":18},"end":{"line":37,"column":82}},"14":{"start":{"line":40,"column":16},"end":{"line":40,"column":53}}},"branchMap":{"1":{"line":2,"type":"if","locations":[{"start":{"line":2,"column":0},"end":{"line":2,"column":0}},{"start":{"line":2,"column":0},"end":{"line":2,"column":0}}]},"2":{"line":2,"type":"binary-expr","locations":[{"start":{"line":2,"column":4},"end":{"line":2,"column":17}},{"start":{"line":2,"column":21},"end":{"line":2,"column":53}}]},"3":{"line":29,"type":"if","locations":[{"start":{"line":29,"column":16},"end":{"line":29,"column":16}},{"start":{"line":29,"column":16},"end":{"line":29,"column":16}}]},"4":{"line":36,"type":"if","locations":[{"start":{"line":36,"column":16},"end":{"line":36,"column":16}},{"start":{"line":36,"column":16},"end":{"line":36,"column":16}}]}}};
}
__cov_9SQU6$TIyGDcy8cuQh5qFA = __cov_9SQU6$TIyGDcy8cuQh5qFA['app/scripts/modules/home/home_module.js'];
__cov_9SQU6$TIyGDcy8cuQh5qFA.s['1']++;if((__cov_9SQU6$TIyGDcy8cuQh5qFA.b['2'][0]++,!this.AppName)||(__cov_9SQU6$TIyGDcy8cuQh5qFA.b['2'][1]++,typeof this.AppName!=='object')){__cov_9SQU6$TIyGDcy8cuQh5qFA.b['1'][0]++;__cov_9SQU6$TIyGDcy8cuQh5qFA.s['2']++;this.AppName={};}else{__cov_9SQU6$TIyGDcy8cuQh5qFA.b['1'][1]++;}__cov_9SQU6$TIyGDcy8cuQh5qFA.s['3']++;(function(){'use strict';__cov_9SQU6$TIyGDcy8cuQh5qFA.f['1']++;__cov_9SQU6$TIyGDcy8cuQh5qFA.s['4']++;AppName.module('HomeModule',function(HomeModule,App,Backbone,Marionette,$,_){__cov_9SQU6$TIyGDcy8cuQh5qFA.f['2']++;__cov_9SQU6$TIyGDcy8cuQh5qFA.s['5']++;HomeModule.Router=Backbone.Marionette.AppRouter.extend({appRoutes:{'':'show','home':'show','about':'about'}});__cov_9SQU6$TIyGDcy8cuQh5qFA.s['6']++;HomeModule.addInitializer(function(options){__cov_9SQU6$TIyGDcy8cuQh5qFA.f['3']++;__cov_9SQU6$TIyGDcy8cuQh5qFA.s['7']++;new HomeModule.Router({controller:HomeModule.API});});__cov_9SQU6$TIyGDcy8cuQh5qFA.s['8']++;HomeModule.API={show:function(options){__cov_9SQU6$TIyGDcy8cuQh5qFA.f['4']++;__cov_9SQU6$TIyGDcy8cuQh5qFA.s['9']++;if(!this.homeController){__cov_9SQU6$TIyGDcy8cuQh5qFA.b['3'][0]++;__cov_9SQU6$TIyGDcy8cuQh5qFA.s['10']++;this.homeController=new HomeModule.Show.Controller(options);}else{__cov_9SQU6$TIyGDcy8cuQh5qFA.b['3'][1]++;}__cov_9SQU6$TIyGDcy8cuQh5qFA.s['11']++;this.homeController.initUi(options);},about:function(options){__cov_9SQU6$TIyGDcy8cuQh5qFA.f['5']++;__cov_9SQU6$TIyGDcy8cuQh5qFA.s['12']++;if(!this.aboutController){__cov_9SQU6$TIyGDcy8cuQh5qFA.b['4'][0]++;__cov_9SQU6$TIyGDcy8cuQh5qFA.s['13']++;this.aboutController=new AboutModule.Show.Controller(options);}else{__cov_9SQU6$TIyGDcy8cuQh5qFA.b['4'][1]++;}__cov_9SQU6$TIyGDcy8cuQh5qFA.s['14']++;this.aboutController.initUi(options);}};});}());
